#!/usr/bin/env python3
"""
gen_decoder_corpus.py — Generate the hostile-input fuzz corpus for
nexrad-decoder's `parse_radial_stream`, mirroring the pattern established by
http-ingest's `fuzz/corpus/parse_response/` (a committed corpus gated on
plain `cargo test`, per S1-W4a in
docs/plans/stage-0-1-close-the-acquisition-path.md).

Base record: `tests/fixtures/kdox_vcp35_end_of_volume.bin` — chosen because
it is the only existing fixture with all seven moment blocks and a full
10-entry block pointer table (RVOL + RELV + RRAD + 7 moments), which gives
every mutation below a real block to target.

Record layout used to compute offsets (see
docs/architecture/nexrad-binary-format.md §4-11):
    record[0:12]    CTM header
    record[12:28]   Message header (size_hw at 12, msg_type at 15)
    record[28:]     Message 31 body
        body[0:32]      Fixed header (num_data_blks at body offset 30)
        body[30:32]     -> record offset 58
        body[32:...]    Block pointer table (vol_ptr @32, el_ptr @36, rad_ptr @40,
                         product ptrs @44...); record offset = body offset + 28

Run once; outputs are committed binary fixtures, not regenerated by CI.

Usage:
    python gen_decoder_corpus.py
"""

import struct
import sys
from pathlib import Path

FIXTURES_DIR = Path(__file__).parent.parent.parent / "crates" / "nexrad-decoder" / "tests" / "fixtures"
CORPUS_DIR = FIXTURES_DIR / "corpus"
BASE_FIXTURE = FIXTURES_DIR / "kdox_vcp35_end_of_volume.bin"

BODY_OFFSET = 28


def load_base() -> bytes:
    return bytearray(BASE_FIXTURE.read_bytes())


def num_data_blks(data: bytes) -> int:
    return struct.unpack_from(">H", data, BODY_OFFSET + 30)[0]


def pointer_table_offsets(data: bytes):
    """Returns (vol_ptr_off, el_ptr_off, rad_ptr_off, [product_ptr_offs])."""
    n = num_data_blks(data)
    n_prod = n - 3
    base = BODY_OFFSET + 32
    return base, base + 4, base + 8, [base + 12 + 4 * i for i in range(n_prod)]


def set_u16(data: bytearray, offset: int, value: int) -> None:
    struct.pack_into(">H", data, offset, value)


def set_u32(data: bytearray, offset: int, value: int) -> None:
    struct.pack_into(">I", data, offset, value)


def write(name: str, data: bytes) -> None:
    out = CORPUS_DIR / name
    out.write_bytes(bytes(data))
    print(f"  wrote {len(data):,} bytes -> {name}")


def main() -> None:
    CORPUS_DIR.mkdir(parents=True, exist_ok=True)

    # -- Golden inputs: the five existing single-record fixtures, unmodified --
    for src in sorted(FIXTURES_DIR.glob("*.bin")):
        write(f"golden_{src.name}", src.read_bytes())

    base = load_base()
    vol_off, el_off, rad_off, prod_offs = pointer_table_offsets(base)
    vol_ptr, el_ptr, rad_ptr = struct.unpack_from(">III", base, vol_off)
    dref_ptr = struct.unpack_from(">I", base, prod_offs[0])[0]

    # -- Truncation at each structural boundary --
    write("hostile_truncated_mid_ctm_header.bin", base[:6])
    write("hostile_truncated_mid_message_header.bin", base[:20])
    write("hostile_truncated_mid_fixed_header.bin", base[:44])
    write("hostile_truncated_mid_pointer_table.bin", base[:80])
    # Mid a moment block's own header (DREF preamble+header spans
    # body[dref_ptr..dref_ptr+28], i.e. before gate data begins).
    write("hostile_truncated_mid_moment_block.bin", base[:BODY_OFFSET + dref_ptr + 10])
    # Mid DREF's gate data (starts at body offset dref_ptr + 28).
    write("hostile_truncated_mid_gate_data.bin", base[:BODY_OFFSET + dref_ptr + 28 + 50])

    # -- Hostile pointer values --
    d = bytearray(base)
    set_u32(d, vol_off, len(d) + 10_000)  # past the end of the body
    write("hostile_pointer_past_end.bin", d)

    d = bytearray(base)
    set_u32(d, vol_off, el_ptr)  # vol_ptr and el_ptr point at each other
    set_u32(d, el_off, vol_ptr)
    write("hostile_pointers_mutual.bin", d)

    d = bytearray(base)
    set_u32(d, vol_off, 4)  # points back into the fixed header itself
    write("hostile_pointer_into_fixed_header.bin", d)

    d = bytearray(base)
    set_u32(d, rad_off, 0xFFFF_FFFF)
    write("hostile_pointer_0xffffffff.bin", d)

    d = bytearray(base)
    set_u32(d, prod_offs[1], 0)  # zero for a block num_data_blks claims exists
    write("hostile_pointer_zero_for_claimed_block.bin", d)

    # -- Hostile counts --
    d = bytearray(base)
    set_u16(d, BODY_OFFSET + 30, 0)
    write("hostile_num_data_blks_0.bin", d)

    d = bytearray(base)
    set_u16(d, BODY_OFFSET + 30, 3)
    write("hostile_num_data_blks_3.bin", d)

    d = bytearray(base)
    set_u16(d, BODY_OFFSET + 30, 65535)
    write("hostile_num_data_blks_65535.bin", d)

    d = bytearray(base)
    set_u16(d, dref_ptr + 8 + BODY_OFFSET, 65535)  # gate_count far exceeds remaining bytes
    write("hostile_gate_count_exceeds_buffer.bin", d)

    d = bytearray(base)
    d[dref_ptr + 19 + BODY_OFFSET] = 24  # word_size neither 8 nor 16
    write("hostile_word_size_invalid.bin", d)

    # -- Hostile framing --
    d = bytearray(base)
    set_u16(d, 12, 0)  # size_hw=0 with msg_type still 31
    write("hostile_size_hw_zero_msg_type_31.bin", d)

    d = bytearray(base)
    set_u16(d, 12, 1)  # size_hw smaller than the message header itself
    write("hostile_size_hw_smaller_than_header.bin", d)

    d = bytearray(base)
    set_u16(d, 12, 60000)  # claimed size runs far past the actual buffer
    write("hostile_size_hw_past_buffer.bin", d)

    d = bytearray(base)
    d[BODY_OFFSET + 21] = 200  # radial_status code not in the known table
    write("hostile_unknown_radial_status.bin", d)

    # -- Degenerate streams --
    write("hostile_all_zero_bytes.bin", bytes(4096))
    write("hostile_all_0xff_bytes.bin", bytes([0xFF]) * 4096)

    print("\nDone.")


if __name__ == "__main__":
    main()
