use nexrad_decoder::{parse_metadata_stream, parse_radial_stream};

// Corpus generated by utility/nexrad-inspect/gen_decoder_corpus.py from the
// real KDOX VCP 35 fixtures already in tests/fixtures/. See that script's
// docstring for how each file was constructed. Mirrors the pattern
// established by http-ingest's fuzz/corpus/parse_response/ (S1-W4a in
// docs/plans/stage-0-1-close-the-acquisition-path.md): a committed corpus
// gated on plain `cargo test`, not a nightly fuzz session someone has to
// remember to run.

fn corpus_dir() -> std::path::PathBuf {
    std::path::Path::new(env!("CARGO_MANIFEST_DIR")).join("tests/fixtures/corpus")
}

fn read_corpus() -> Vec<Vec<u8>> {
    let dir = corpus_dir();
    std::fs::read_dir(&dir)
        .unwrap_or_else(|e| panic!("could not read corpus dir {dir:?}: {e}"))
        .map(|entry| std::fs::read(entry.expect("readable dir entry").path()).expect("readable corpus file"))
        .collect()
}

#[test]
fn corpus_never_panics() {
    let corpus = read_corpus();
    assert!(!corpus.is_empty(), "corpus directory should not be empty");
    for data in &corpus {
        let _ = parse_radial_stream(data); // must not panic
        let _ = parse_metadata_stream(data); // must not panic
    }
}

#[test]
fn mutated_inputs_never_panic() {
    let seeds = read_corpus();
    assert!(!seeds.is_empty());

    let mut rng = fuzz_support::XorShift64::new(0x2545_F491_4F6C_DD1D);
    for _ in 0..5000 {
        let mutated = fuzz_support::mutate_one(&mut rng, &seeds);
        let _ = parse_radial_stream(&mutated); // must not panic
        let _ = parse_metadata_stream(&mutated); // must not panic
    }
}
