#!/usr/bin/env python3
"""Generate crates/radar-workstation/src/sites_generated.rs from the committed
NOAA HOMR NEXRAD station export (data/nexrad-stations.txt).

Usage:
    python3 utility/nexrad-sites/generate.py

Regenerating from a fresh source export: re-download
https://www.ncei.noaa.gov/access/homr/file/nexrad-stations.txt into
data/nexrad-stations.txt, then re-run this script. See utility/README.md for
provenance (retrieval date, license) and the exact download command.

This is dev-only tooling (see utility/README.md) — not built, imported, or run
by anything in crates/. Its only output is the committed generated file.
"""
from __future__ import annotations

import pathlib

SCRIPT_DIR = pathlib.Path(__file__).resolve().parent
SOURCE_FILE = SCRIPT_DIR / "data" / "nexrad-stations.txt"
OUTPUT_FILE = SCRIPT_DIR.parent.parent / "crates" / "radar-workstation" / "src" / "sites_generated.rs"

# Column boundaries (0-indexed, half-open) in the fixed-width HOMR export,
# derived from the header/separator lines rather than hardcoded blindly —
# see the assertion in main() that re-derives and cross-checks them.
COLUMNS = {
    "icao": (9, 13),
    "name": (20, 50),
    "state": (72, 74),
    "lat": (106, 115),
    "lon": (116, 126),
    "elev_ft": (127, 133),
    "stntype": (140, 190),
}

FEET_TO_METERS = 0.3048


def parse_column_boundaries(separator_line: str) -> dict[str, tuple[int, int]]:
    """Re-derive column boundaries from the export's own `----` separator
    line, so a source file with reflowed columns fails loudly (via the
    assertion in main()) instead of silently misparsing fields."""
    boundaries = []
    start = None
    for i, ch in enumerate(separator_line + " "):
        if ch == "-" and start is None:
            start = i
        elif ch != "-" and start is not None:
            boundaries.append((start, i))
            start = None
    names = ["ncdcid", "icao", "wban", "name", "country", "state", "county", "lat", "lon", "elev_ft", "utc", "stntype"]
    return dict(zip(names, boundaries))


def main() -> None:
    lines = SOURCE_FILE.read_text(encoding="utf-8").splitlines()
    derived = parse_column_boundaries(lines[1])
    for key in COLUMNS:
        assert derived[key] == COLUMNS[key], (
            f"column layout drifted for {key}: expected {COLUMNS[key]}, "
            f"source now has {derived[key]} — update COLUMNS before regenerating"
        )

    sites = []
    for line in lines[2:]:
        if not line.strip():
            continue
        stntype = line[COLUMNS["stntype"][0]:COLUMNS["stntype"][1]].strip()
        if stntype != "NEXRAD":
            continue  # excludes TDWR and any other station type (Restraint is a Feature)
        icao = line[COLUMNS["icao"][0]:COLUMNS["icao"][1]].strip()
        name = line[COLUMNS["name"][0]:COLUMNS["name"][1]].strip()
        state = line[COLUMNS["state"][0]:COLUMNS["state"][1]].strip()
        lat = float(line[COLUMNS["lat"][0]:COLUMNS["lat"][1]].strip())
        lon = float(line[COLUMNS["lon"][0]:COLUMNS["lon"][1]].strip())
        elev_ft = float(line[COLUMNS["elev_ft"][0]:COLUMNS["elev_ft"][1]].strip())
        elevation_m = round(elev_ft * FEET_TO_METERS)

        assert len(icao) == 4 and icao.isalnum(), f"unexpected ICAO id {icao!r}"
        assert '"' not in name and "\\" not in name, f"name needs escaping: {name!r}"

        sites.append((icao, name, state, lat, lon, elevation_m))

    assert sites, "no NEXRAD rows found — source export format may have changed"
    ids = [s[0] for s in sites]
    assert len(ids) == len(set(ids)), "duplicate ICAO id in source export"
    sites.sort(key=lambda s: s[0])  # sites::by_id's binary search requires this

    lines_out = [
        "// Generated by utility/nexrad-sites/generate.py — do not hand-edit.",
        "// Source: NOAA NCEI HOMR NEXRAD station export (public domain). See",
        "// utility/README.md for provenance and the regeneration command.",
        "",
        "use crate::sites::Site;",
        "",
        f"pub static SITES: &[Site] = &[",
    ]
    for icao, name, state, lat, lon, elevation_m in sites:
        lines_out.append(
            f'    Site {{ id: "{icao}", name: "{name}", state: "{state}", '
            f"lat: {lat}, lon: {lon}, elevation_m: {elevation_m} }},"
        )
    lines_out.append("];")
    lines_out.append("")

    OUTPUT_FILE.write_text("\n".join(lines_out), encoding="utf-8")
    print(f"wrote {len(sites)} sites to {OUTPUT_FILE}")


if __name__ == "__main__":
    main()
